### PR TITLE
Fix documentation about references

### LINKED ISSUE #267: Update documentation
https://github.com/atlassian/smith/pull/262 makes some documentation examples obsolete. And I guess not just examples, also new syntax needs to be explained.

### PR DESCRIPTION
**Pull request by ash2k**
Fixes #267.

### CODE REVIEW

File: pkg/controller/bundlec_test/resolve_binding_secret_references_test.go [hunk 1]
```diff
@@ -131,32 +104,77 @@ func TestResolveBindingSecretReferences(t *testing.T) {
...
-									Kind:       "ServiceInstance",
-									APIVersion: sc_v1b1.SchemeGroupVersion.String(),
+									Kind:       "ConfigMap",
+									APIVersion: core_v1.SchemeGroupVersion.String(),
 								},
 								ObjectMeta: meta_v1.ObjectMeta{
-									Name: si2,
+									Name: mapNeedsAnUpdate,
 									Annotations: map[string]string{
-										"Secret": "{{" + resSb1 + ":bindsecret#Data.mysecret}}",
```
Comment (ash2k) [inline pkg/controller/bundlec_test/resolve_binding_secret_references_test.go]: This test should have been failing but it was not. Bundle was updated to add the missing finalizer (see around line 64) and the reference was not processed. In fact, the reference format is old here - test test should have been updated when the references refactoring was performed. I've expanded this test to assert the bundle conditions to make sure it does not regress in the future. Also checked if all other tests do have the finalizer specified (there is one that does not intentionally - it tests the the finalizer is added).

File: docs/design/field-references.md [hunk 2]
```diff
@@ -42,27 +49,30 @@ spec:
...
           name: sleeper3
-        spec: "{{sleeper2#spec}}"
+        spec: "!{sleeper2-spec}"
 ```
 
 ## Referring to ServiceBinding outputs
 
-When Service Catalog processes a ServiceBinding, the output is placed in a Secret
+When Service Catalog processes a `ServiceBinding`, the output is placed in a `Secret`
 (since they might be secret). If they're not secret, it's convenient to directly
```
Comment (nilebox) [inline docs/design/field-references.md]: "they may contain sensitive data"

**Comment by nilebox** [comment]
@ash2k you need to run `make check` to see linter errors.

File: docs/design/field-references.md (hunk 2 above)
Comment (ash2k) [reply docs/design/field-references.md]: This text is originally from James, so I'm confident it is grammatically correct 😛

Comment (wryun) [reply docs/design/field-references.md]: Don't trust me! I am super-prone to making mistakes. I type slightly more quickly than I think in most cases.

But I think Nail here is not suggesting a grammatical change, but one which avoids the confusion of Secret vs secret, which I probably wrote just because it amused me. His version is better!
